### ISSUE TITLE
dnf module install samba fails

### ISSUE THREAD

**Issue by alexxa** [modularity-modules/samba#1]
Error: 
 Problem: conflicting requests
  - nothing provides python2-dns needed by python2-samba-2:4.7.0-0.9.rc5.module_97fb54be.x86_64

**Comment by alexxa** [comment]
@KarstenHopp

**Comment by alexxa** [comment]
The error msg changed to: 

(item=samba) =>

Problem 1: conflicting requests  - nothing provides libtalloc.so.2()(64bit) needed by libldb-1.3.0-2.module_8789fd86.x86_64

Problem 2: conflicting requests  - nothing provides libtalloc.so.2()(64bit) needed by samba-libs-2:4.7.0-14.module_8789fd86.x86_64

Problem 3: conflicting requests  - nothing provides libtalloc.so.2()(64bit) needed by libsmbclient-2:4.7.0-14.module_8789fd86.x86_64

Problem 4: conflicting requests  - nothing provides libtalloc.so.2()(64bit) needed by samba-dc-libs-2:4.7.0-14.module_8789fd86.x86_64

Problem 5: conflicting requests  - nothing provides libtalloc.so.2()(64bit) needed by samba-common-tools-2:4.7.0-14.module_8789fd86.x86_64

Problem 6: conflicting requests  - nothing provides libtalloc.so.2()(64bit) needed by samba-client-libs-2:4.7.0-14.module_8789fd86.x86_64

Problem 7: conflicting requests  - nothing provides libtalloc.so.2()(64bit) needed by samba-winbind-2:4.7.0-14.module_8789fd86.x86_64

Problem 8: conflicting requests  - nothing provides libtalloc.so.2()(64bit) needed by samba-2:4.7.0-14.module_8789fd86.x86_64

Problem 9: conflicting requests  - nothing provides libtalloc.so.2()(64bit) needed by samba-common-libs-2:4.7.0-14.module_8789fd86.x86_64

Problem 10: conflicting requests  - nothing provides libtalloc.so.2()(64bit) needed by samba-winbind-modules-2:4.7.0-14.module_8789fd86.x86_64

Problem 11: conflicting requests  - nothing provides libtalloc.so.2()(64bit) needed by python2-samba-2:4.7.0-14.module_8789fd86.x86_64

Problem 12: package libwbclient-2:4.7.0-14.module_8789fd86.x86_64 requires libreplace-samba4.so()(64bit), but none of the providers can be installedn  - conflicting requestsn  - nothing provides libtalloc.so.2()(64bit) needed by samba-client-libs-2:4.7.0-14.module_8789fd86.x86_64

Also see a similar issue with sssd:  https://github.com/modularity-modules/sssd/issues/4

**Comment by nphilipp** [comment]
If sssd needs it, too, should libtalloc go into its own (engineering) module, or is there some existing collective module it could go into? (@KarstenHopp ?)

**Comment by nphilipp** [comment]
NB, here's the fedmod-generated modulemd:

```
data:
  api:
    rpms:
    - libtalloc
  components:
    rpms:
      libtalloc:
        buildorder: 10
        rationale: Package in api
  dependencies:
    requires:
      platform: f27
      samba: f27
  description: A library that implements a hierarchical allocator with destructors.
  license:
    content:
    - LGPLv3+
    module:
    - MIT
  summary: The talloc library
document: modulemd
version: 1
```
